# detect-cameras.ps1
# Lists all DirectShow video devices visible to FFmpeg,
# then writes cameras.conf pre-filled with ALL detected cameras.

$ErrorActionPreference = "Stop"
$ffmpeg    = "$PSScriptRoot\tools\ffmpeg\bin\ffmpeg.exe"
$confFile  = "$PSScriptRoot\cameras.conf"

if (-not (Test-Path $ffmpeg)) {
    Write-Error "FFmpeg not found at $ffmpeg`nPlease run setup.ps1 first."
    exit 1
}

Write-Host "Querying DirectShow video devices via FFmpeg..."
Write-Host ""

# FFmpeg prints the device list to stderr; redirect stderr -> stdout to capture it
$rawOutput = & $ffmpeg -list_devices true -f dshow -i dummy 2>&1 | Out-String

# Parse lines like:  [dshow @ 0x...] "My Camera Name" (video)
$devices = [System.Collections.Generic.List[string]]::new()
foreach ($line in ($rawOutput -split "`n")) {
    if ($line -match '"(.+?)" \(video\)') {
        $devices.Add($Matches[1])
    }
}

if ($devices.Count -eq 0) {
    Write-Warning "No DirectShow video devices found."
    Write-Host ""
    Write-Host "Troubleshooting tips:"
    Write-Host "  - Make sure all webcams are plugged in and recognised by Windows"
    Write-Host "  - Open Device Manager and check for any camera errors"
    Write-Host "  - Try running this script as Administrator"
    exit 1
}

Write-Host "Found $($devices.Count) video device(s):"
for ($i = 0; $i -lt $devices.Count; $i++) {
    Write-Host "  [$($i + 1)] $($devices[$i])"
}
Write-Host ""

# Build cameras.conf - one block per detected camera
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# cameras.conf - Generated by detect-cameras.ps1")
$lines.Add("# Edit the values below if needed, then run start-streams.ps1")
$lines.Add("# Add or remove CAMERA blocks to include/exclude cameras.")
$lines.Add("")

for ($i = 0; $i -lt $devices.Count; $i++) {
    $n      = $i + 1
    $name   = $devices[$i]
    $stream = "cam$n"
    $lines.Add("# --- Camera $n ---")
    $lines.Add("# The exact DirectShow device name (case-sensitive)")
    $lines.Add("CAMERA${n}_NAME=$name")
    $lines.Add("# The RTSP path ZoneMinder will use:  rtsp://<host>:8554/<stream>")
    $lines.Add("CAMERA${n}_STREAM=$stream")
    $lines.Add("")
}

$lines.Add("# --- Encoding Settings (applied to all cameras) ---")
$lines.Add("# Target average bitrate in kbps per stream.")
$lines.Add("# 8000 = ~8 Mbit/s (high quality 1080p).  Raise to 12000-20000 for 4K.")
$lines.Add("BITRATE=8000")
$lines.Add("")
$lines.Add("# Maximum bitrate cap (kbps) - typically 1.5-2x BITRATE to absorb peaks")
$lines.Add("MAXRATE=12000")
$lines.Add("")
$lines.Add("# Force a specific resolution, e.g. 1920x1080  (leave blank = camera native)")
$lines.Add("RESOLUTION=")
$lines.Add("")
$lines.Add("# Force a specific framerate, e.g. 30  (leave blank = camera native)")
$lines.Add("FRAMERATE=")
$lines.Add("")
$lines.Add("# H.264 CRF quality: 0=lossless, 18=visually lossless, 23=default, 28=fast")
$lines.Add("# Lower = better quality AND larger file/stream size.")
$lines.Add("# 18 is the recommended sweet-spot for best quality.")
$lines.Add("CRF=18")
$lines.Add("")
$lines.Add("# x264 preset: ultrafast / superfast / veryfast / faster / fast / medium")
$lines.Add("# Slower preset = better compression at same quality, but more CPU usage.")
$lines.Add("# veryfast is a solid balance for real-time capture.")
$lines.Add("PRESET=veryfast")

$lines | Set-Content $confFile -Encoding UTF8

Write-Host "cameras.conf written to $confFile  ($($devices.Count) camera(s) configured)"
Write-Host ""
Write-Host "Review the file, then run  .\start-streams.ps1  to start broadcasting."
Write-Host ""
