# detect-cameras.ps1
# Lists all DirectShow video devices visible to FFmpeg,
# then writes cameras.conf pre-filled with the first two cameras found.

$ErrorActionPreference = "Stop"
$ffmpeg    = "$PSScriptRoot\tools\ffmpeg\bin\ffmpeg.exe"
$confFile  = "$PSScriptRoot\cameras.conf"

if (-not (Test-Path $ffmpeg)) {
    Write-Error "FFmpeg not found at $ffmpeg`nPlease run setup.ps1 first."
    exit 1
}

Write-Host "Querying DirectShow video devices via FFmpeg..."
Write-Host ""

# FFmpeg prints the device list to stderr; redirect stderr -> stdout to capture it
$rawOutput = & $ffmpeg -list_devices true -f dshow -i dummy 2>&1 | Out-String

# Parse lines like:  [dshow @ 0x...] "My Camera Name" (video)
$devices = [System.Collections.Generic.List[string]]::new()
foreach ($line in ($rawOutput -split "`n")) {
    if ($line -match '"(.+?)" \(video\)') {
        $devices.Add($Matches[1])
    }
}

if ($devices.Count -eq 0) {
    Write-Warning "No DirectShow video devices found."
    Write-Host ""
    Write-Host "Troubleshooting tips:"
    Write-Host "  - Make sure both webcams are plugged in and recognised by Windows"
    Write-Host "  - Open Device Manager and check for any camera errors"
    Write-Host "  - Try running this script as Administrator"
    exit 1
}

Write-Host "Found $($devices.Count) video device(s):"
for ($i = 0; $i -lt $devices.Count; $i++) {
    Write-Host "  [$($i + 1)] $($devices[$i])"
}
Write-Host ""

if ($devices.Count -lt 2) {
    Write-Warning "Only one camera detected. Connect the second webcam and re-run."
    exit 1
}

# Build cameras.conf
$cam1 = $devices[0]
$cam2 = $devices[1]

$confContent = @"
# cameras.conf - Generated by detect-cameras.ps1
# Edit the values below if needed, then run start-streams.ps1

# --- Camera 1 ---
# The exact DirectShow device name (case-sensitive)
CAMERA1_NAME=$cam1
# The RTSP path ZoneMinder will use:  rtsp://<host>:8554/<stream>
CAMERA1_STREAM=cam1

# --- Camera 2 ---
CAMERA2_NAME=$cam2
CAMERA2_STREAM=cam2

# --- Encoding Settings ---
# Target average bitrate in kbps per stream.
# 8000 = ~8 Mbit/s (high quality 1080p).  Raise to 12000-20000 for 4K.
BITRATE=8000

# Maximum bitrate cap (kbps) - typically 1.5-2x BITRATE to absorb peaks
MAXRATE=12000

# Force a specific resolution, e.g. 1920x1080  (leave blank = camera native)
RESOLUTION=

# Force a specific framerate, e.g. 30  (leave blank = camera native)
FRAMERATE=

# H.264 CRF quality: 0=lossless, 18=visually lossless, 23=default, 28=fast
# Lower = better quality AND larger file/stream size.
# 18 is the recommended sweet-spot for best quality.
CRF=18

# x264 preset: ultrafast / superfast / veryfast / faster / fast / medium
# Slower preset = better compression at same quality, but more CPU usage.
# veryfast is a solid balance for real-time capture.
PRESET=veryfast
"@

$confContent | Set-Content $confFile -Encoding UTF8

Write-Host "cameras.conf written to $confFile"
Write-Host ""
Write-Host "Review the file, then run  .\start-streams.ps1  to start broadcasting."
Write-Host ""
