#!/usr/bin/env bash
# start-streams.sh
# Reads cameras.conf, starts MediaMTX, then launches one FFmpeg process per camera.
# Supports any number of cameras defined in cameras.conf.
# Keep this terminal open while streaming. Press Ctrl+C to stop everything cleanly.
#
# Requires: ffmpeg, mediamtx  (see README-LINUX.md for setup)

set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FFMPEG="ffmpeg"
MEDIAMTX="$SCRIPT_DIR/tools/mediamtx/mediamtx"
MEDIAMTX_YML="$SCRIPT_DIR/tools/mediamtx/mediamtx.yml"
MEDIAMTX_DIR="$SCRIPT_DIR/tools/mediamtx"
CONF_FILE="$SCRIPT_DIR/cameras.conf"

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------

if ! command -v ffmpeg &>/dev/null; then
    echo ""
    echo "ERROR: ffmpeg is not installed."
    echo "Install with:  sudo apt install ffmpeg"
    echo ""
    exit 1
fi

if [[ ! -x "$MEDIAMTX" ]]; then
    echo ""
    echo "ERROR: MediaMTX not found at $MEDIAMTX"
    echo "Download the Linux binary from https://github.com/bluenviron/mediamtx/releases"
    echo "and place mediamtx in tools/mediamtx/"
    echo ""
    exit 1
fi

if [[ ! -f "$CONF_FILE" ]]; then
    echo ""
    echo "ERROR: cameras.conf not found."
    echo "Run ./detect-cameras.sh first."
    echo ""
    exit 1
fi

mkdir -p "$MEDIAMTX_DIR"

# ---------------------------------------------------------------------------
# Parse cameras.conf
# ---------------------------------------------------------------------------

declare -A CONF

while IFS='=' read -r key value; do
    # Skip comments and blank lines
    [[ "$key" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${key// }" ]]           && continue
    key="${key#"${key%%[![:space:]]*}"}"   # ltrim
    key="${key%"${key##*[![:space:]]}"}"   # rtrim
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    CONF["$key"]="$value"
done < "$CONF_FILE"

conf_get() {
    local key="$1" default="${2:-}"
    echo "${CONF[$key]:-$default}"
}

BITRATE=$(conf_get BITRATE 8000)
MAXRATE=$(conf_get MAXRATE 12000)
CRF=$(conf_get CRF 18)
PRESET=$(conf_get PRESET veryfast)
RESOLUTION=$(conf_get RESOLUTION "")
FRAMERATE=$(conf_get FRAMERATE "")
BUFSIZE=$((MAXRATE * 2))

# Discover all CAMERA<n>_DEVICE keys
declare -a CAM_DEVICES=()
declare -a CAM_STREAMS=()
n=1
while true; do
    dev=$(conf_get "CAMERA${n}_DEVICE" "")
    [[ -z "$dev" ]] && break
    stream=$(conf_get "CAMERA${n}_STREAM" "cam${n}")
    CAM_DEVICES+=("$dev")
    CAM_STREAMS+=("$stream")
    n=$((n+1))
done

if [[ ${#CAM_DEVICES[@]} -eq 0 ]]; then
    echo ""
    echo "ERROR: No CAMERA1_DEVICE found in cameras.conf."
    echo "Run ./detect-cameras.sh first."
    echo ""
    exit 1
fi

echo "[Config] Found ${#CAM_DEVICES[@]} camera(s) in cameras.conf."

# ---------------------------------------------------------------------------
# Write mediamtx.yml
# ---------------------------------------------------------------------------

{
    echo "# mediamtx.yml - auto-generated by start-streams.sh"
    echo ""
    echo "logLevel: info"
    echo "logDestinations: [stdout]"
    echo ""
    echo "rtsp: yes"
    echo "rtspAddress: :8554"
    echo 'rtspEncryption: "no"'
    echo ""
    echo "rtmp: no"
    echo "hls: no"
    echo "webrtc: no"
    echo "srt: no"
    echo ""
    echo "paths:"
    for stream in "${CAM_STREAMS[@]}"; do
        echo "  ${stream}:"
        echo "    source: publisher"
    done
} > "$MEDIAMTX_YML"

echo "[Config] mediamtx.yml written (${#CAM_STREAMS[@]} path(s))."

# ---------------------------------------------------------------------------
# Build FFmpeg argument array for a camera
# Usage: build_ffmpeg_args /dev/video0 cam1
# Prints arguments one per line (caller reads into array)
# ---------------------------------------------------------------------------

build_ffmpeg_args() {
    local device="$1"
    local stream_path="$2"

    # Input
    echo "-f"
    echo "v4l2"
    echo "-thread_queue_size"
    echo "512"

    if [[ -n "$RESOLUTION" ]]; then
        echo "-video_size"
        echo "$RESOLUTION"
    fi
    if [[ -n "$FRAMERATE" ]]; then
        echo "-framerate"
        echo "$FRAMERATE"
    fi

    echo "-i"
    echo "$device"

    # Encoding
    echo "-c:v"
    echo "libx264"
    echo "-preset"
    echo "$PRESET"
    echo "-tune"
    echo "zerolatency"
    echo "-crf"
    echo "$CRF"
    echo "-maxrate"
    echo "${MAXRATE}k"
    echo "-bufsize"
    echo "${BUFSIZE}k"
    echo "-pix_fmt"
    echo "yuv420p"
    echo "-an"

    # Output
    echo "-f"
    echo "rtsp"
    echo "-rtsp_transport"
    echo "tcp"
    echo "rtsp://localhost:8554/${stream_path}"
}

# ---------------------------------------------------------------------------
# Cleanup handler - kill everything on Ctrl+C
# ---------------------------------------------------------------------------

MEDIAMTX_PID=""
declare -a FFMPEG_PIDS=()

cleanup() {
    echo ""
    echo "Stopping all processes..."
    for pid in "${FFMPEG_PIDS[@]:-}"; do
        [[ -n "$pid" ]] && kill "$pid" 2>/dev/null && echo "  Stopped FFmpeg PID $pid"
    done
    [[ -n "$MEDIAMTX_PID" ]] && kill "$MEDIAMTX_PID" 2>/dev/null && echo "  Stopped MediaMTX PID $MEDIAMTX_PID"
    echo "All stopped."
    exit 0
}

trap cleanup INT TERM

# ---------------------------------------------------------------------------
# Start MediaMTX
# ---------------------------------------------------------------------------

echo "[MediaMTX] Starting RTSP server..."
"$MEDIAMTX" "$MEDIAMTX_YML" \
    > "$MEDIAMTX_DIR/mediamtx.log" \
    2> "$MEDIAMTX_DIR/mediamtx-err.log" &
MEDIAMTX_PID=$!

sleep 2

if ! kill -0 "$MEDIAMTX_PID" 2>/dev/null; then
    echo ""
    echo "ERROR: MediaMTX exited immediately."
    echo ""
    echo "--- mediamtx output ---"
    tail -20 "$MEDIAMTX_DIR/mediamtx.log"   2>/dev/null || true
    tail -10 "$MEDIAMTX_DIR/mediamtx-err.log" 2>/dev/null || true
    echo "--- end of log ---"
    echo ""
    echo "Possible causes:"
    echo "  - Port 8554 already in use  (check: ss -tlnp | grep 8554)"
    echo "  - mediamtx.yml could not be read"
    exit 1
fi

echo "[MediaMTX] Running (PID $MEDIAMTX_PID)"

# ---------------------------------------------------------------------------
# Start FFmpeg for each camera
# ---------------------------------------------------------------------------

declare -a CAM_ARGS_FILES=()   # temp files holding args, one per line
declare -a CAM_LOG_ERR=()

for i in "${!CAM_DEVICES[@]}"; do
    n=$((i+1))
    dev="${CAM_DEVICES[$i]}"
    stream="${CAM_STREAMS[$i]}"
    log_err="$MEDIAMTX_DIR/ffmpeg-cam${n}-err.log"
    log_out="$MEDIAMTX_DIR/ffmpeg-cam${n}-out.log"
    args_file="$(mktemp /tmp/ffmpeg-cam${n}-args.XXXXXX)"

    build_ffmpeg_args "$dev" "$stream" > "$args_file"
    CAM_ARGS_FILES+=("$args_file")
    CAM_LOG_ERR+=("$log_err")

    # Read args from file into array (handles spaces correctly)
    mapfile -t args < "$args_file"

    echo "[Camera $n] Starting: $dev  ->  rtsp://localhost:8554/$stream"
    ffmpeg "${args[@]}" \
        > "$log_out" \
        2> "$log_err" &
    FFMPEG_PIDS+=($!)
    sleep 3   # give device time to enumerate before opening next
done

sleep 1

# ---------------------------------------------------------------------------
# Show connection info
# ---------------------------------------------------------------------------

LOCAL_IP=$(ip -4 route get 1.0.0.0 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)
LOCAL_IP="${LOCAL_IP:-<your-ip>}"

echo ""
echo "========================================================="
echo " Streams are live!  (${#CAM_DEVICES[@]} camera(s))"
echo "========================================================="
echo ""
for i in "${!CAM_DEVICES[@]}"; do
    n=$((i+1))
    echo "  Camera $n: rtsp://${LOCAL_IP}:8554/${CAM_STREAMS[$i]}"
done
echo ""
echo "Add each URL as a monitor in ZoneMinder:"
echo "  Source Type : FFmpeg"
echo "  Source Path : rtsp://${LOCAL_IP}:8554/<stream>"
echo ""
echo "Press Ctrl+C to stop all streams."
echo "========================================================="
echo ""

# ---------------------------------------------------------------------------
# Monitor loop - watch for unexpected exits, auto-restart FFmpeg on crash
# ---------------------------------------------------------------------------

while true; do
    sleep 5

    # Check MediaMTX
    if ! kill -0 "$MEDIAMTX_PID" 2>/dev/null; then
        echo "WARNING: MediaMTX (PID $MEDIAMTX_PID) exited unexpectedly."
        echo "--- mediamtx log (last 20 lines) ---"
        tail -20 "$MEDIAMTX_DIR/mediamtx.log" 2>/dev/null || true
        echo "--- end ---"
        # MediaMTX is not auto-restarted — streams cannot continue without it
        cleanup
    fi

    # Check each FFmpeg process
    for i in "${!FFMPEG_PIDS[@]}"; do
        pid="${FFMPEG_PIDS[$i]}"
        n=$((i+1))
        if [[ -n "$pid" ]] && ! kill -0 "$pid" 2>/dev/null; then
            echo "WARNING: FFmpeg Camera $n (PID $pid) exited unexpectedly."
            log_err="${CAM_LOG_ERR[$i]}"
            if [[ -f "$log_err" ]]; then
                echo "--- ffmpeg-cam${n} log (last 30 lines) ---"
                tail -30 "$log_err"
                echo "--- end ---"
            fi

            echo "[Auto-restart] Restarting Camera $n in 3 seconds..."
            sleep 3

            dev="${CAM_DEVICES[$i]}"
            stream="${CAM_STREAMS[$i]}"
            log_out="$MEDIAMTX_DIR/ffmpeg-cam${n}-out.log"
            args_file="${CAM_ARGS_FILES[$i]}"
            mapfile -t args < "$args_file"

            ffmpeg "${args[@]}" \
                > "$log_out" \
                2> "$log_err" &
            new_pid=$!
            FFMPEG_PIDS[$i]=$new_pid
            echo "[Auto-restart] Camera $n restarted (PID $new_pid)."
        fi
    done
done
