# start-streams.ps1
# Reads cameras.conf, starts MediaMTX, then launches one FFmpeg process per camera.
# Keep this window open while streaming. Press Ctrl+C to stop everything cleanly.

$ErrorActionPreference = "Stop"
$scriptDir    = $PSScriptRoot
$ffmpeg       = "$scriptDir\tools\ffmpeg\bin\ffmpeg.exe"
$mediamtxExe  = "$scriptDir\tools\mediamtx\mediamtx.exe"
$mediamtxYml  = "$scriptDir\mediamtx.yml"
$confFile     = "$scriptDir\cameras.conf"

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------

foreach ($f in @($ffmpeg, $mediamtxExe, $confFile)) {
    if (-not (Test-Path $f)) {
        Write-Error "Missing required file: $f`nMake sure you have run setup.ps1 and detect-cameras.ps1 first."
        exit 1
    }
}

# ---------------------------------------------------------------------------
# Parse cameras.conf
# ---------------------------------------------------------------------------

$conf = @{}
Get-Content $confFile |
    Where-Object { $_ -notmatch '^\s*#' -and $_ -match '^\s*\w+\s*=' } |
    ForEach-Object {
        $parts = $_ -split '=', 2
        $conf[$parts[0].Trim()] = $parts[1].Trim()
    }

function Conf($key, $default = '') {
    if ($conf.ContainsKey($key) -and $conf[$key] -ne '') { return $conf[$key] }
    return $default
}

$cam1Name   = Conf "CAMERA1_NAME"
$cam1Stream = Conf "CAMERA1_STREAM" "cam1"
$cam2Name   = Conf "CAMERA2_NAME"
$cam2Stream = Conf "CAMERA2_STREAM" "cam2"
$bitrate    = Conf "BITRATE"   "8000"
$maxrate    = Conf "MAXRATE"   "12000"
$crf        = Conf "CRF"       "18"
$preset     = Conf "PRESET"    "veryfast"
$resolution = Conf "RESOLUTION"
$framerate  = Conf "FRAMERATE"

if (-not $cam1Name -or -not $cam2Name) {
    Write-Error "CAMERA1_NAME or CAMERA2_NAME is empty in cameras.conf."
    exit 1
}

# ---------------------------------------------------------------------------
# Write mediamtx.yml
# ---------------------------------------------------------------------------

$ymlContent = @"
# mediamtx.yml - auto-generated by start-streams.ps1

logLevel: info
logDestinations: [stdout]

# RTSP server
rtsp: yes
rtspAddress: :8554
rtspEncryption: no

# Disable unused protocols to reduce overhead
rtmp: no
hls: no
webrtc: no
srt: no

# Stream paths - FFmpeg pushes to these, ZoneMinder reads from them
paths:
  $($cam1Stream):
    source: publisher
  $($cam2Stream):
    source: publisher
"@

$ymlContent | Set-Content $mediamtxYml -Encoding UTF8
Write-Host "[Config] mediamtx.yml written."

# ---------------------------------------------------------------------------
# Build FFmpeg argument lists
# ---------------------------------------------------------------------------

function Build-FFmpegArgs {
    param (
        [string]$CameraName,
        [string]$StreamPath
    )

    $args = [System.Collections.Generic.List[string]]@(
        "-f", "dshow",
        "-rtbufsize", "256M"   # large ring buffer to avoid dropped frames
    )

    # Optional overrides
    if ($resolution) { $args.AddRange([string[]]@("-video_size", $resolution)) }
    if ($framerate)  { $args.AddRange([string[]]@("-framerate",  $framerate))  }

    $args.AddRange([string[]]@(
        "-i", "video=$CameraName",

        # H.264 encoding - visually lossless quality
        "-c:v", "libx264",
        "-preset", $preset,
        "-tune", "zerolatency",     # minimise latency (important for live monitoring)
        "-crf", $crf,               # quality target (18 = visually lossless)
        "-maxrate", "${maxrate}k",  # bitrate cap for network headroom
        "-bufsize", "$([int]$maxrate * 2)k",
        "-pix_fmt", "yuv420p",      # broadest decoder compatibility

        # RTSP output to MediaMTX
        "-f", "rtsp",
        "-rtsp_transport", "tcp",
        "rtsp://localhost:8554/$StreamPath"
    ))

    return $args.ToArray()
}

$ffmpegArgs1 = Build-FFmpegArgs -CameraName $cam1Name -StreamPath $cam1Stream
$ffmpegArgs2 = Build-FFmpegArgs -CameraName $cam2Name -StreamPath $cam2Stream

# ---------------------------------------------------------------------------
# Start MediaMTX
# ---------------------------------------------------------------------------

Write-Host "[MediaMTX] Starting RTSP server..."
$mediamtxProc = Start-Process `
    -FilePath $mediamtxExe `
    -ArgumentList @($mediamtxYml) `
    -PassThru `
    -WindowStyle Normal

Start-Sleep -Seconds 2

if ($mediamtxProc.HasExited) {
    Write-Error "MediaMTX exited immediately. Check the MediaMTX window for errors."
    exit 1
}
Write-Host "[MediaMTX] Running (PID $($mediamtxProc.Id))"

# ---------------------------------------------------------------------------
# Start FFmpeg for each camera
# ---------------------------------------------------------------------------

Write-Host "[Camera 1] Starting: $cam1Name  ->  rtsp://localhost:8554/$cam1Stream"
$ffmpegProc1 = Start-Process `
    -FilePath $ffmpeg `
    -ArgumentList $ffmpegArgs1 `
    -PassThru `
    -WindowStyle Normal

Start-Sleep -Seconds 1

Write-Host "[Camera 2] Starting: $cam2Name  ->  rtsp://localhost:8554/$cam2Stream"
$ffmpegProc2 = Start-Process `
    -FilePath $ffmpeg `
    -ArgumentList $ffmpegArgs2 `
    -PassThru `
    -WindowStyle Normal

Start-Sleep -Seconds 2

# ---------------------------------------------------------------------------
# Show connection info
# ---------------------------------------------------------------------------

$localIp = (
    Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object {
        $_.InterfaceAlias -notlike "*Loopback*" -and
        $_.PrefixOrigin   -ne "WellKnown"       -and
        $_.IPAddress      -notlike "169.254.*"
    } |
    Sort-Object -Property InterfaceMetric |
    Select-Object -First 1
).IPAddress

Write-Host ""
Write-Host "========================================================="
Write-Host " Streams are live!"
Write-Host "========================================================="
Write-Host ""
Write-Host "  Camera 1:  rtsp://${localIp}:8554/$cam1Stream"
Write-Host "  Camera 2:  rtsp://${localIp}:8554/$cam2Stream"
Write-Host ""
Write-Host "Add these as monitors in ZoneMinder:"
Write-Host "  Source Type : FFmpeg"
Write-Host "  Source Path : rtsp://${localIp}:8554/<stream>"
Write-Host ""
Write-Host "Press Ctrl+C to stop all streams."
Write-Host "========================================================="
Write-Host ""

# ---------------------------------------------------------------------------
# Monitor loop - watch for unexpected exits and clean up on Ctrl+C
# ---------------------------------------------------------------------------

$procs = @(
    @{ Name = "MediaMTX";  Proc = $mediamtxProc },
    @{ Name = "Camera 1";  Proc = $ffmpegProc1  },
    @{ Name = "Camera 2";  Proc = $ffmpegProc2  }
)

try {
    while ($true) {
        Start-Sleep -Seconds 5
        foreach ($entry in $procs) {
            if ($entry.Proc.HasExited) {
                Write-Warning "$($entry.Name) (PID $($entry.Proc.Id)) exited unexpectedly (code $($entry.Proc.ExitCode))."
            }
        }
    }
}
finally {
    Write-Host ""
    Write-Host "Stopping all processes..."
    foreach ($entry in $procs) {
        if (-not $entry.Proc.HasExited) {
            Write-Host "  Stopping $($entry.Name) (PID $($entry.Proc.Id))..."
            Stop-Process -Id $entry.Proc.Id -Force -ErrorAction SilentlyContinue
        }
    }
    Write-Host "All stopped. Goodbye."
}
